### ISSUE TITLE
Extension hangs on hover

### ISSUE THREAD

**Issue by maxno-kivra** [erlang-ls/vscode#30] opened 2020-02-20 18:23 UTC
Go to definition works fine, until I hover over a dependency, then it gets stuck. Cancelling the hover/trying to go to definition (F12) is also stuck at this point making the extension a bit useless.

Which is unfortunate because everything else is so nice :)

---

I tried it in a smaller repo, and then it works, which makes me believe the indexing is not fast enough. But I don't have time to wait for it to finish right now.

The most important thing here is that cancelling the hover should be enough to make it work again.

**Comment by robertoaloi** [comment] 2020-02-20 21:56
Hi @maxno-kivra and thanks for getting in touch.

The indexing process will soon be revisited, but for now you will have to allow it to complete before you can start interacting with the server.

The indexed information is persisted to disk and files which are already indexed are not re-parsed if their content is unchanged, so the indexing will take a long time only the first time you open a big project.

Cancellation is not implemented, so `F12` will not do anything.

Do you mind sharing your [logs](https://github.com/erlang-ls/erlang_ls#troubleshooting) when this happens, so we can understand what's happening? Feel free to obfuscate sensitive info (e.g. source code, module names, etc).

**Comment by maxno-kivra** [comment] 2020-02-21 11:51
Just compiled a debug version from latest master, and what's really strange is that the logs indicate it is successful in finding the hover information. But VS Code still says loading. Kinda like TCP head-of-line blocking.

**Comment by maxno-kivra** [comment] 2020-03-02 11:25
Still having issues in our large repo. The annoying thing is that the server seems to keep responding to requests. But somewhere in the cancellation request flow it gets stuck.

Also, it would be nice to get an notification/status bar update saying that the indexing is done. Even better to be able to force it to reindex the current project. The official Python extension have a spinner in the status bar, looking at bit like ♻️

**Comment by jfacorro** [comment] 2020-03-02 15:05
I have experienced this behaviour today, although I'm not sure how I got to get it. But what I noticed is that not only the hover hangs, everything else stops working as well (e.g. auto-complete, go to defintion, find references, ...). Do you have the same experience?

**Comment by maxno-kivra** [comment] 2020-03-02 15:39
Yes, precisely. As soon as you hover, it goes to sleep.

**Comment by jfacorro** [comment] 2020-03-02 20:36
I saw the same behaviour but now I can't seem to be able to reproduce it. Do you have some pointers on steps to reproduce the issue @maxno-kivra?

**Comment by maxno-kivra** [comment] 2020-03-03 08:39
I just open the repo in question and hover over any third party library, e.g. `cowboy:start_tls/3` -> `_build/default/lib/cowboy/src/cowboy.erl`.

**Comment by jfacorro** [comment] 2020-03-03 12:32
Thank you, I'm now able to reproduce this consistenly. This behaviour is very strange.

**Comment by jfacorro** [comment] 2020-03-03 15:14
I've been able to reproduce in particular when hovering on the usage of `jsx:decode/2`, **but** hovering over some other external dependencies works just fine (e.g. `cow_http:parse_headers/1`). 

So far my best guess is that something breaks internally in the client, possilby because of some syntax error that some specific files have. For example when I open `jsx.erl` in VS Code the syntax highlighting towards the end of the file seems broken (e.g. the last `-endif.` is not being highlighted correctly). 

Even more strange is that if I delete almost all of the content of `jsx.erl` except the `-module(jsx).`, then hovering over the usage of `jsx:decode/2` starts working. 🤯

**Comment by maxno-kivra** [comment] 2020-03-04 14:05
Ok, that makes more sense. But then it should give back some sort of failure message to VS Code so that the hover fails rather then stalls.

**Comment by jfacorro** [comment] 2020-03-04 15:07
@kvadym  found the issue. Something other than Erlang LS is printing to `stdout` which makes it fail with `Error: Header must provide a Content-Length property.`. We need to find a way to isolate or limit the processes that can write to stdout.

**Comment by jfacorro** [comment] 2020-03-04 15:55
Issue created in erlang-ls/erlang_ls#518.

**Comment by maxno-kivra** [comment] 2020-03-04 16:11
Fantastic detective work @jfacorro, thank you. Hope this turns out to be decently easy to fix.

**Comment by jfacorro** [comment] 2020-03-04 16:30
It was all possible because @kvadym found a way to get the error console in VS Code, I think I would have spent countless more hours trying to get my head around this otherwise.

**Comment by jfacorro** [comment] 2020-03-06 11:10
The bug is now fixed in the `master` branch of [`erlang_ls`](https://github.com/erlang-ls/erlang_ls) it will be available in the next release of the VS Code extension.

**Comment by maxno-kivra** [comment] 2020-03-10 10:28
Lovely, thanks ❤️

**Comment by robertoaloi** [comment] 2020-03-11 14:46
Fixed in `0.0.10`.

**Closed by robertoaloi** 2020-03-11 14:46 UTC
Labels: bug
